# Generated by Django 3.2.12 on 2023-09-28 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kutubxona', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authormodel',
            old_name='place_of_birth',
            new_name='date_of_birth',
        ),
    ]
