# Generated by Django 3.2.12 on 2023-09-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kutubxona', '0002_rename_place_of_birth_authormodel_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookmodel',
            table=None,
        ),
    ]
