# Generated by Django 3.2.12 on 2023-09-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kutubxona', '0003_alter_bookmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookmodel',
            table='Book',
        ),
    ]
