# Generated by Django 3.2.12 on 2023-09-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutubxona', '0004_alter_bookmodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='name',
            field=models.CharField(max_length=101),
        ),
    ]
