# Generated by Django 4.1.7 on 2023-09-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutubxona', '0004_alter_bookmodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
