# Generated by Django 4.1.7 on 2023-09-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kutubxona', '0005_alter_authormodel_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authormodel',
            old_name='dateofbirth',
            new_name='date_of_death',
        ),
    ]
